-- ============================================================
-- Oracle DBA Lab
-- Users, Roles & Privileges
--
-- File: 03_create_application_objects.sql
--
-- Purpose:
-- Create application objects owned by APP_OWNER.
--
-- This script creates a sample CUSTOMERS table and inserts
-- test data that will later be accessed by APP_READER through
-- APP_READONLY_ROLE.
--
-- Run this script as APP_OWNER inside XEPDB1.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Verify current user
-- ------------------------------------------------------------

SELECT USER
FROM dual;


-- ------------------------------------------------------------
-- 2. Verify current container
-- ------------------------------------------------------------

SHOW CON_NAME;


-- ------------------------------------------------------------
-- 3. Create CUSTOMERS table
-- ------------------------------------------------------------

CREATE TABLE customers (
    customer_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    full_name VARCHAR2(100)
        NOT NULL,

    email VARCHAR2(150)
        NOT NULL,

    created_at DATE
        DEFAULT SYSDATE
        NOT NULL,

    CONSTRAINT pk_customers
        PRIMARY KEY (customer_id),

    CONSTRAINT uq_customers_email
        UNIQUE (email)
);


-- ------------------------------------------------------------
-- 4. Insert sample data
-- ------------------------------------------------------------

INSERT INTO customers (
    full_name,
    email
)
VALUES (
    'Ana Torres',
    'ana.torres@example.com'
);


INSERT INTO customers (
    full_name,
    email
)
VALUES (
    'Carlos Soto',
    'carlos.soto@example.com'
);


INSERT INTO customers (
    full_name,
    email
)
VALUES (
    'Daniela Rojas',
    'daniela.rojas@example.com'
);


COMMIT;


-- ------------------------------------------------------------
-- 5. Verify table data
-- ------------------------------------------------------------

SELECT
    customer_id,
    full_name,
    email,
    created_at
FROM customers
ORDER BY customer_id;


-- ------------------------------------------------------------
-- 6. Verify created object
-- ------------------------------------------------------------

SELECT
    object_name,
    object_type,
    status
FROM user_objects
WHERE object_name = 'CUSTOMERS';


-- ------------------------------------------------------------
-- 7. Verify table ownership
-- ------------------------------------------------------------

SELECT
    table_name
FROM user_tables
WHERE table_name = 'CUSTOMERS';